<div class="div_box">
    <ul class="ul_path">
        <li><a href="#">Quản lý chung</a><span>»</span></li>
        <li><a href="#">Cập nhật quảng cáo bên trái</a><span></span></span></li>
    </ul>
</div>
<div class="div_box">
    <span class="span_tieude">Cập nhật quảng cáo bên trái</span>
    <a href="javascript:window.history.back();" title="Trở về trang trước">
		<div class="div_command">
			<div class="div_command_icon">
				<img src="<?=$this->baseUrl("/img")?>/back.png"/>
			</div>
			<p class="p_command_text">Trở về</p>
		</div>
	</a>
</div>

<div class="div_box">
    <?=$this->notify?>
    <?=$this->form?>
	<div class="img-slide">
        <canvas id="canvas"></canvas>
    </div>
</div>

<script>
    $(function(){        
        var canvas = document.getElementById("canvas");
        var context = canvas.getContext("2d");
        var img = new Image();
        img.onload = function(){
            context.drawImage(this,0,0,this.width,this.height,0,0,canvas.width,canvas.height);
        }
        img.src = "<?php echo $this->baseUrl((!isset($this->thumb)||$this->thumb=="")?"/img/no-img.jpg":"upload/".$this->thumb);?>";
        
        /*Select new image */
        $('#image').change(function(e) {
            var file = e.target.files[0],
                imageType = /image.*/;
    
            if (!file.type.match(imageType))
                return;
    
            var reader = new FileReader();
            reader.onload = fileOnload;
            reader.readAsDataURL(file);        
        });
    
        function fileOnload(e) {
            var canvas = $('#canvas')[0];
            var context = canvas.getContext('2d');
            
            var $img = new Image();
            $img.onload= function() {
                canvas.width = canvas.width;
                context.drawImage(this, 0, 0,this.width,this.height,0,0,canvas.width,canvas.height);
            };
            $img.src = e.target.result;
        }
    });
</script>