<div class="div_box">
    <ul class="ul_path">
        <li><a href="#">Quản lý chung</a><span>»</span></li>
        <li class="current"><a href="#">Quản lý sản phẩm</a></li>
    </ul>
</div>
<div class="div_box">
    <span class="span_tieude">Quản lý sản phẩm</span>
    <a href="javascript:window.history.back();" title="Trở về trang trước">
		<div class="div_command">
			<div class="div_command_icon">
				<img src="<?=$this->baseUrl("/img")?>/back.png"/>
			</div>
			<p class="p_command_text">Trở về</p>
		</div>
	</a>
    <a href="<?=$this->baseUrl("/admin/index/insert-prods")?>" title="Thêm mới">
		<div class="div_command">
			<div class="div_command_icon">
				<img src="<?=$this->baseUrl("/img")?>/Add.png.gif"/>
			</div>
			<p class="p_command_text">Thêm mới</p>
		</div>
	</a>
</div>
<div class="div_box">
    <table id="GridView_TblMain" class="GridView_TblMain" cellspacing="0" cellpadding="0" border="0">
        <thead>
            <tr class="GridView_TrTitle">
                <th class="center" style="width: 40px;">STT</th>
                <th>Tên sản phẩm</th>
				<th>Giá</th>
				<th class="center" style="width: 80px;">Ẩn/Hiện Giá</th>
                <th style="width: 100px;">Người đăng</th>
                <th class="center" style="width: 130px;">Ngày đăng</th>
                <th class="center" style="width: 80px;">Trạng thái</th>
                <th class="center" style="width: 90px;">Thao tác</th>
            </tr>
        </thead>
        <tbody>
            <?=$this->notify?>
            <?foreach($this->datas as $key=>$row){?>
                <tr>
                    <td class="center"><?=$key+1?></td>
                    <td><?=$row->product_name?></td>
					<td><?=$row->product_price?></td>
					<td class="center">
                        <a class="status-price" rel="<?=$row->product_id?>"><span class="icon icon-color <?=$row->prod_price_status?"icon-close":"icon-check";?>"></span></a>
                    </td>
                    <td><?=$row->fullname?></td>
                    <td class="center"><?=date("d/m/Y - H:s:i",strtotime($row->product_date))?></td>
                    <td class="center">
                        <a class="status" rel="<?=$row->product_id?>"><span class="icon icon-color <?=$row->product_status?"icon-close":"icon-check";?>"></span></a>
                    </td>
                    <td class="center">
                        <a href="<?=$this->baseUrl("/admin/index/edit-prods/id/$row->product_id")?>"><i class="icon-edit"></i>Sửa</a> | 
                        <a href="#" rel="<?=$row->product_id?>" class="del"><i class="icon-trash"></i>Xóa</a>
                    </td>
                </tr>
            <?}?>                
        </tbody>
    </table>
    <?=$this->paginationControl($this->datas,"Sliding","pagination/pagination-control.phtml")?>
</div>
<script>
    $(function(){
       $(".status").click(function(){
        var id = $(this).attr("rel");
        $.get("<?=$this->baseUrl("/admin/index/status-prods")?>",{idprod:id},function(){},"json");
       });
	   $(".status-price").click(function(){
        var id = $(this).attr("rel");
		var clickObj = $(this);
		var iconObject = clickObj.find(".icon");
        $.get("<?=$this->baseUrl("/admin/index/status-prodsprice")?>",{idprod:id},function(response){
			if(response == 1){
				iconObject.removeClass("icon-check");
				iconObject.addClass("icon-close");
			}else{
				iconObject.addClass("icon-check");
				iconObject.removeClass("icon-close");
			}
		},"json");
       });
       $(".del").click(function(){
            var id = $(this).attr("rel");
            if(confirm("Bạn muốn xóa danh mục này?")){
                $(this).parent("td").parent("tr").remove();
                $.get("<?=$this->baseUrl("admin/index/del-prods")?>",{idprod:id},function(){},"json");
            }            
       });
    });
</script>
<div class="div_box">
    <a href="javascript:window.history.back();" title="Trở về trang trước">
		<div class="div_command">
			<div class="div_command_icon">
				<img src="<?=$this->baseUrl("/img")?>/back.png"/>
			</div>
			<p class="p_command_text">Trở về</p>
		</div>
	</a>
    <a href="<?=$this->baseUrl("/admin/index/insert-prods")?>" title="Thêm mới">
		<div class="div_command">
			<div class="div_command_icon">
				<img src="<?=$this->baseUrl("/img")?>/Add.png.gif"/>
			</div>
			<p class="p_command_text">Thêm mới</p>
		</div>
	</a>
</div>