<div class="md-box md-box-8 float-right">      
    <div class="">
        <ol class="breadcrumb" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
            <li><a itemprop="url" class="home" href="<?= $this->baseUrl("/") ?>"><span itemprop="title"> Trang chủ </span></a></li>
            <li class="active" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><span itemprop="title"><?= $this->pname ?></span></li>
        </ol>
        <?php 
            $auth = Zend_Auth::getInstance();
            $identity = $auth->getIdentity();
        ?>
        <div class="news-wap">
            <form action="" method="post" name="form_customer" id="form_customer">
                <legend style="border-bottom: none"><h4><?= $this->pname ?></h4></legend>	  
                <div class="news-content">
                    <table class="table table-customer">
                        <thead>
                            <tr>
                                <th>THÔNG TIN NGƯỜI MUA</th>
                                <th>THÔNG TIN NGƯỜI NHẬN</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <div class="info-buyer" style="margin-left: 10px">
                                        <div class="control-group">
                                            <label class="control-label" for="fullname">Họ tên <span class="tred">(*)</span></label>
                                            <div class="controls">
                                                <input class="small clear" value="<?=$identity->fullname?>" type="text" name="fullname" id="fullname" placeholder="Họ và tên"/>
                                            </div>
                                            <label class="control-label" for="phone">Điện thoại <span class="tred">(*)</span></label>
                                            <div class="controls">
                                                <input class="small clear" value="<?=$identity->phone?>" type="text" name="phone" id="phone" placeholder="Điện thoại"/>
                                            </div>
                                            <label class="control-label" for="email">Email <span class="tred">(*)</span></label>
                                            <div class="controls">
                                                <input class="small clear" value="<?=$identity->email?>" type="email" name="email" id="email" placeholder="Email"/>
                                            </div>
                                            <label class="control-label" for="address">Địa chỉ <span class="tred">(*)</span></label>
                                            <div class="controls">
                                                <input class="small clear" value="<?=$identity->address?>" type="text" name="address" id="address" placeholder="Địa chỉ"/>
                                            </div>
                                            <div class="clearfix"></div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="info-receive" style="margin-left: 10px;display: none">
                                        <div class="control-group">
                                            <label class="control-label" for="fullname">Họ tên <span class="tred">(*)</span></label>
                                            <div class="controls">
                                                <input class="small clear" value="<?=$identity->fullname?>" type="text" name="fullname" id="fullname" placeholder="Họ và tên"/>
                                            </div>
                                            <label class="control-label" for="phone">Điện thoại <span class="tred">(*)</span></label>
                                            <div class="controls">
                                                <input class="small clear" value="<?=$identity->phone?>" type="text" name="phone" id="phone" placeholder="Điện thoại"/>
                                            </div>
                                            <label class="control-label" for="email">Email <span class="tred">(*)</span></label>
                                            <div class="controls">
                                                <input class="small clear" value="<?=$identity->email?>" type="email" name="email" id="email" placeholder="Email"/>
                                            </div>
                                            <label class="control-label" for="address">Địa chỉ <span class="tred">(*)</span></label>
                                            <div class="controls">
                                                <input class="small clear" value="<?=$identity->address?>" type="text" name="address" id="address" placeholder="Địa chỉ"/>
                                            </div>
                                            <div class="clearfix"></div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <!--<td colspan="2" class="al choose-otheraddress">
                                    <div class="col-md-2"></div>
                                    <input checked="checked" name="other_address" id="other_address_no" type="radio" value="no">
                                    <label for="other_address_no"> Người nhận là quý khách</label>&nbsp;&nbsp;
                                    <input name="other_address" type="radio" id="other_address_yes" value="yes">
                                    <label for="other_address_yes"> Địa chỉ khác</label>
                                </td> -->
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="2" class="ac">
                                    <textarea style="width: 90%;" name="bill_notes" rows="5" placeholder="Ghi chú"></textarea>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <legend style="border-bottom: none"><h4>Chọn phương thức thanh toán</h4></legend>
                <div class="news-content">
                    <table class="table table-striped table-payment">
                        <thead>
                            <tr>
                                <th style="width: 100px"></th>
                                <th style="width: 200px;">Loại</th>
                                <th>Mô tả</th>
                                <th style="width: 100px;">Giao dịch</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><img src="<?=$this->baseUrl("/")?>img/pay-cod.jpg"/></td>
                                <td>Thanh toán khi giao hàng</td>
                                <td></td>
                                <td>
                                    <input checked="checked" type="radio" value="1" name="bill_type_pay">
                                </td>
                            </tr>
                            <tr>
                                <td><img src="<?=$this->baseUrl("/")?>img/pay-bank.jpg"/></td>
                                <td>Chuyển khoản ngân hàng</td>
                                <td></td>
                                <td>
                                    <input type="radio" value="0" name="bill_type_pay">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </form>
            <legend style="border-bottom: none"><h4>Sản phẩm đặt mua</h4></legend>
            <div class="news-content">
                <input type="hidden" name="id" value="0" />
                <table class="table table-cart">
                    <thead>
                        <tr>
                            <th>Sản phẩm</th>
                            <th>Đơn giá</th>
                            <th>Số lượng</th>
                            <th>Thành tiền</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $path = PUBLIC_PATH . "/upload/";
                        $sums = 0;
                        if (!empty($this->cartItems)) {
                            foreach ($this->cartItems as $id => $item) {
                                ?>
                                <tr>
                                    <td>
                                        <?php if (is_file($path . $item->product_image)) { ?>
                                            <img src="<?= $this->baseUrl("") ?>timthumb.php?src=<?= $this->baseUrl("/upload/$item->product_image&amp;w=90&amp;h=100") ?>" />
                                        <?php } else { ?>    
                                            <img src="<?= $this->baseUrl("") ?>timthumb.php?src=<?= $this->baseUrl("/img/no-img.jpg&amp;w=90&amp;h=100") ?>" />
                                        <?php } ?>
                                        <h4><?= $item->product_name ?></h4>
                                    </td>
                                    <td><?= number_format($item->product_price, 0, ".", ",") ?> VNĐ</td>
                                    <td>
                                        <input style="width: 70px;height: 30px;text-align: center" disabled="true" type="text" value="<?=$item->qty?>"/>
                                    </td>
                                    <td><?=number_format($item->sum, 0, ".", ",")?> VNĐ</td>
                                </tr>
                            <?php }
                        }else{
                            ?>
                                <tr>
                                    <td colspan="5"><i>Chưa có sản phẩm nào trong giỏ hàng</i></td>
                                </tr>
                                <?php
                        }
                        ?>
                    </tbody>
                </table>
                <div class="cart-total">
                    <div class="row">
                        <div class="col-md-6"></div>
                        <div class="col-md-6 cart-total-price">
                            <div class="row row-total-price">
                                <div class="col-md-8">
                                    <strong>Tổng tiền thanh toán </strong></br>
                                    <span class="text-description-total-price" style="font-size: 11px !important;">(Giá chưa bao gồm thuế)</span>
                                </div>
                                <div class="col-md-4">
                                    <div class="subtotal-price al" style=" font-size: 17px !important; "><span class="price"><?=number_format($this->sums, 0, ".", ",")?></span> VNĐ</div>
                                </div>
                            </div>
                            <div class="row checkout-payment">
                                <div class="button-checkout ar">
                                    <a class="btn btn-success float-right" style="margin-right: 15px" href="<?=$this->baseUrl("/xac-nhan-don-hang/")?>"><i class="glyphicon glyphicon-play"></i> TIẾP TỤC THANH TOÁN</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> 
</div>
<div class="clear"></div>