<div class="md-box md-box-8 float-right">      
    <div class="">
        <ol class="breadcrumb" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
            <li><a itemprop="url" class="home" href="<?= $this->baseUrl("/") ?>"><span itemprop="title"> Trang chủ </span></a></li>
            <li class="active" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><span itemprop="title"><?= $this->pname ?></span></li>
        </ol>
        <div class="news-wap">
            <fieldset>
                <legend><h4><?= $this->pname ?></h4></legend>
                <?php 
                    $auth = Zend_Auth::getInstance();
                    $identity = $auth->getIdentity();
                ?>
                <div class="news-content">
                    <?php if (!empty($this->flashmsgs)) { ?>
                        <div class="alert alert-success">
                            <ul>
                                <?php foreach ($this->flashmsgs as $message) { ?>
                                    <li><?php echo $message; ?></li>
                                <?php } ?>
                            </ul>
                        </div>
                    <?php } ?>
                    <a class="btn btn-danger pull-right" href="javascript:window.history.back()" style="margin-bottom: 15px">Tiếp tục mua hàng</a>
                    <form action="<?=$this->baseUrl("/gio-hang?act=updateAll")?>" method="post">
                        <input type="hidden" name="id" value="0" />
                    <table class="table table-striped table-cart">
                        <thead>
                            <tr>
                                <th>Sản phẩm</th>
                                <th>Đơn giá</th>
                                <th>Số lượng</th>
                                <th>Thành tiền</th>
                                <th>Xóa</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $path = PUBLIC_PATH . "/upload/";
                            $sums = 0;
                            if (!empty($this->cartItems)) {
                                foreach ($this->cartItems as $id => $item) {
                                    ?>
                                    <tr>
                                        <td>
                                            <?php if (is_file($path . $item->product_image)) { ?>
                                                <img src="<?= $this->baseUrl("") ?>timthumb.php?src=<?= $this->baseUrl("/upload/$item->product_image&amp;w=90&amp;h=100") ?>" />
                                            <?php } else { ?>    
                                                <img src="<?= $this->baseUrl("") ?>timthumb.php?src=<?= $this->baseUrl("/img/no-img.jpg&amp;w=90&amp;h=100") ?>" />
                                            <?php } ?>
                                            <h4><?= $item->product_name ?></h4>
                                        </td>
                                        <td><?= number_format($item->product_price, 0, ".", ",") ?> VNĐ</td>
                                        <td>
                                            <input style="height: 30px;text-align: center" type="number" name="items[<?=$id?>]" min="1" max="<?=$item->product_qty + 1?>" value="<?=$item->qty?>"/>
                                            <p><?=$item->store_status?></p>
                                        </td>
                                        <td><?=number_format($item->sum, 0, ".", ",")?> VNĐ</td>
                                        <td><a href="<?= $this->baseUrl("/gio-hang") . "?act=del&id={$item->id}" ?>"><i class="glyphicon glyphicon-remove"></i> </a></td>
                                    </tr>
                                <?php }
                            }else{
                                ?>
                                    <tr>
                                        <td colspan="5"><i>Chưa có sản phẩm nào trong giỏ hàng</i></td>
                                    </tr>
                                    <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr><td colspan="5" style="text-align: right;font-size: 18px;"><h3>Tổng tiền</h3></br><?=number_format($this->sums, 0, ".", ",")?> VNĐ</td></tr>
                        </tfoot>
                    </table>
                    <div class="btn-group pull-right">
                        <input class="btn btn-primary" type="submit" value="CẬP NHẬT GIỎ HÀNG"/>
                        <a class="btn btn-success" href="<?php if(!isset($identity)){echo $this->baseUrl("/dang-ky");}else{echo $this->baseUrl("/chi-tiet-gio-hang");}?>"><i class="glyphicon glyphicon-play"></i> THANH TOÁN</a>
                    </div>
                    </form>
                </div>			
            </fieldset>
        </div>
    </div> 
</div>
<div class="clear"></div>