<div class="md-box md-box-8 float-right"> 
	<div class="">
		<ol class="breadcrumb" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
			<li><a itemprop="url" class="home" href="<?=$this->baseUrl("/")?>"><span itemprop="title"> Trang chủ </span></a></li>
			<li class="active" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><span itemprop="title">Liên hệ</span></li>
		</ol>
		<div class="news-wap" style="">		
			<?=$this->notify;?>
			<fieldset>
				<legend><h4>Thông tin liên hệ</h4></legend>			
				<div class="news-content">
					<b>Địa chỉ :</b> 28 Trịnh Lỗi, P.Phú Thọ Hòa, Q.Tân Phú, Tp.Hồ Chí Minh<br />
					<b>Điện thoại :</b> (08) 22148787 - (08) 22148797 - (08) 22121250 <br />
					<b>Hotline :</b> 0903341666 - 982158634<br />
					<b>Fax :</b> (08) 39789687<br />
					<b>Email :</b> saigonsao.hcm@gmail.com - saigonsao_hcm@yahoo.com
				</div>   
			</fieldset>
		</div><!--end thông tin-->          
		<div class="news-wap" style="">
			<fieldset>
				<legend><h4>Liên hệ</h4></legend>	
				<div class="news-content">
					<form id="form-contact" class="form-horizontal" action="" method="post">
						<div class="control-group">
							<label class="control-label" for="email">Email <span class="tred">(*)</span></label>
							<div class="controls">
								<input class="input-xlarge" type="text" name="email" id="email" placeholder="Email"/>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="control-group">
							<label class="control-label" for="fullname">Họ tên <span class="tred">(*)</span></label>
							<div class="controls">
								<input class="input-xlarge" type="text" name="fullname" id="fullname" placeholder="Họ tên"/>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="control-group">
							<label class="control-label" for="title">Tiêu đề <span class="tred">(*)</span></label>
							<div class="controls">
								<input class="input-xlarge" type="text" name="title" id="title" placeholder="Tiêu đề"/>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="control-group">
							<label class="control-label" for="content">Nội dung <span class="tred">(*)</span></label>
							<div class="controls">
								<textarea rows="5" class="input-xlarge" id="content" name="content"></textarea>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="control-group">
							<label class="control-label" for="captcha"><?php
								echo $st1 = rand(0,9); echo " + "; echo $st2 = rand(0,9); echo " = ";
							?></label>
							<div class="controls">
								<input class="input-xlarge" type="text" name="captcha" id="captcha" placeholder="Kết quả"/>
								<input type="hidden" id="recaptcha" name="recaptcha" value="<?=$st1+$st2?>" />
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="control-group">
							<button type="submit" class="btn">Gửi</button>
						</div>
					</form>
				</div>
				<div class="clear"></div>
			</fieldset>
		</div>  <!--end liên hệ-->   
		<div class="news-wap" style="">
			<fieldset>
				<legend><h4>Bản đồ</h4></legend>        
				<div class="news-content">                       
					<div id="single_map_canvas" style="width:100%; height:590px">
						<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
						<script>    
					 
						  function init_map() {
							var var_location = new google.maps.LatLng(10.7888772,106.6232534);
					 
							var var_mapoptions = {
							  center: var_location,
							  zoom: 14
							};
					 
							var var_marker = new google.maps.Marker({
								position: var_location,
								map: var_map,
								title:"Venice"});
					 
							var var_map = new google.maps.Map(document.getElementById("single_map_canvas"),
								var_mapoptions);
					 
							var_marker.setMap(var_map);    
					 
						  }
					 
						  google.maps.event.addDomListener(window, 'load', init_map);
					 
						</script>
					</div>
				</div>    
			</fieldset>    
		</div><!--end bản đồ-->   
	</div>  
</div>
<div class="clear"></div>