<div class="md-box md-box-8 float-right">      
    <div class="">
        <ol class="breadcrumb" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
            <li><a itemprop="url" class="home" href="<?= $this->baseUrl("/") ?>"><span itemprop="title"> Trang chủ </span></a></li>
            <li class="active" itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><span itemprop="title"><?= $this->pname ?></span></li>
        </ol>
        <div class="news-wap">
            <fieldset>
                <legend><h4><?= $this->pname ?></h4></legend>
                <div class="news-content">
                    <a class="btn btn-danger pull-right" href="javascript:window.history.back()" style="margin-bottom: 15px">Tiếp tục mua hàng</a>
                    <h4>Cám ơn quý khách đã đặt hàng</br>
                        Mọi thông tin xin liên hệ:</h4>
                    <p>Địa chỉ : 28 Trịnh Lỗi, P.Phú Thọ Hòa, Q.Tân Phú, Tp.Hồ Chí Minh</br>
                        Điện thoại : (08) 22148787 - (08) 22148797 - (08) 22121250 </br>
                        <b style="color: red">Hotline :</b> (08) 22148787</br>
                        Fax : (08) 39789687</br>
                        Email : saigonsao.hcm@gmail.com - saigonsao_hcm@yahoo.com</br>
                    </p>
                </div>			
            </fieldset>
        </div>
    </div> 
</div>
<div class="clear"></div>