<div class="products" style="margin-top:-17px;">
	<?php
		$model = new Application_Model_DbTable_Products();
		$datas = $model->fetchAll($model->getProducts()->where("product_status=?",1)->order("product_date DESC")->limit(12));
	?>
	<h2>Sản phẩm mới</h2>
	<div style="border:1px solid #eee;">
	<?php $path = PUBLIC_PATH."/upload/"; foreach($datas as $row){?>
		<div class="product col-xs-3 col-sm-3">
			<div>
				<div class="image-news" style="">
					<a href="<?=$this->baseUrl("/san-pham/{$row->product_alias}/")?>">
					<?php if(is_file($path.$row->product_image)){?>
						<img src="<?=$this->baseUrl("")?>timthumb.php?src=<?=$this->baseUrl("/upload/$row->product_image&amp;w=150&amp;h=170")?>" />
					<?}else{?>    
						<img src="<?=$this->baseUrl("")?>timthumb.php?src=<?=$this->baseUrl("/img/no-img.jpg&amp;w=150&amp;h=170")?>" />
					<?}?>   
					</a>       
				</div>
				<div class="news-content">
					<h6><a style="color:red;font-weight:bolder;" href="<?=$this->baseUrl("/san-pham/{$row->product_alias}/")?>"><?=$row->product_name?></a></h6>
					<?php if($row->prod_price_status == 1){?>
						<h6><a style="color:black;" href="<?=$this->baseUrl("/{$row->pcate_alias}/{$row->product_alias}/")?>">Giá: <?= number_format($row->product_price, 0, ".", ",")?></a></h6>
					<?}else{?>
						<h6></br><a style="color:black;" href="<?=$this->baseUrl("/{$row->pcate_alias}/{$row->product_alias}/")?>"> </a></h6>
					<?}?>
					<div class="button">
						<a href="<?=$this->baseUrl("/san-pham/{$row->product_alias}/")?>" class="btn btn-sm btn-primary bolder">Chi tiết</a>
						<a class="btn btn-sm btn-danger bolder" rel="331" href="<?=$this->baseUrl("/gio-hang")."?act=add&id={$row->product_id}"?>"><i class="fa fa-plus"></i> Giỏ hàng</a>
					</div>
				</div>  
			</div> 
		</div>
	<?}?>
		<div class="clearfix"></div>
	</div>
</div>