<?php
    $model = new Application_Model_DbTable_Config();
    $configF = $model->getConfigFace();
?>
<?php if(isset($configF['facebook']) && $configF['facebook'] != ""){?>
	<div class="side-bar">
		<h2>Chúng tôi trên facebook</h2>
		<div>
			<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2F<?=$configF['facebook'];?>&amp;width&amp;height=258&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false&amp;appId=776560995697372" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:258px;width:100%;" allowTransparency="true"></iframe>
		</div>
	</div>
<?php }?>