<?php
    $model = new Application_Model_DbTable_Articles();
    $select = $model->select();
    $select->where("article_type=?","hotro")->where("article_status=?",1);
    $datas = $model->fetchAll($select);
?>
<?php if(count($datas) > 0){?>
	<div class="side-bar">
		<h2>Hổ trợ trực tuyến</h2>
		<div class="hotro">
			<?php foreach($datas as $row){?>
                            <div>
                                <a href="Skype:<?=$row->article_detail?>?chat" style="float: left"> 
                                    <img src="http://mystatus.skype.com/mediumicon/<?=$row->article_detail?>" mce_href="Skype:<?=$row->article_detail?>?chat" title="" width="50" height="30" alt="">
				</a>
				<a href="ymsgr:sendim?<?=$row->article_alias?>" mce_href="ymsgr:sendim?<?=$row->article_alias?>" border="0">
                                    <img src="http://opi.yahoo.com/online?u=<?=$row->article_alias?>&t=2" mce_src="http://opi.yahoo.com/online?u=<?=$row->article_alias?>&t=2"></br>
				</a>
                            </div>
                            <div style="width: 355px;padding-right: 170px;padding-bottom: 15px;padding-top: 5px;"><?=$row->article_title?> - <span style="font-weight:boler;color:red;"><?=$row->article_description?></span></div>
			<?php }?>
		</div>
	</div>
<?php }?>