<ul id="nav">
	<li class="top"><a class="top_link" href="<?=$this->baseUrl("/")?>"><span class="down"><img style="margin-bottom: 5px;margin-right: 4px;height: 26px;" src="<?=$this->baseUrl("/img/home.png")?>" style="height:20px;"> Trang chủ</span></a></li>
    <li class="top"><a class="top_link" href="<?=$this->baseUrl("/gioi-thieu/")?>"><span class="down">Giới thiệu</span></a></li>
	<li class="top"><a class="top_link" href="<?=$this->baseUrl("/tat-ca-san-pham/")?>"><span class="down">Sản phẩm</span></a></li>
	<li class="top"><a class="top_link" href="<?=$this->baseUrl("/tin-tuc/")?>"><span class="down">Tin tức</span></a></li>  
    <li class="top"><a class="top_link" href="<?=$this->baseUrl("/tuyen-dung/")?>"><span class="down">Tuyển dụng</span></a></li>
    <li class="top"><a class="top_link" href="<?=$this->baseUrl("/lien-he/")?>"><span class="down">Liên hệ</span></a></li>
</ul>