<ul id="nav">
    <li class="top active"><a class="top_link" href="<?=$this->baseUrl("/")?>"><span class="down"><img style="margin-bottom: 5px;margin-right: 4px;height: 26px;" src="<?=$this->baseUrl("/img/home.png")?>" style="height:20px;"> Trang chủ</span></a></li>
    <li class="top"><a class="top_link" href="<?=$this->baseUrl("/gioi-thieu/")?>"><span class="down">Giới thiệu</span></a></li>
    <li class="top"><a class="top_link" href="<?=$this->baseUrl("/nha-cung-cap/")?>"><span class="down">Nhà Cung cấp</span></a></li>
    <li class="top"><a class="top_link" href="<?=$this->baseUrl("/khach-hang/")?>"><span class="down">Khách hàng</span></a></li>
    <li class="top"><a class="top_link" href="<?=$this->baseUrl("/tat-ca-san-pham/")?>"><span class="down">Sản phẩm</span></a></li>
    <li class="top"><a class="top_link" href="<?=$this->baseUrl("/lien-he/")?>"><span class="down">Liên hệ</span></a></li>
    <li class="top"><a class="top_link" href="<?=$this->baseUrl("/tuyen-dung/")?>"><span class="down">Tuyển dụng</span></a></li>
    <li class="top"><a class="top_link" href="<?=$this->baseUrl("/qua-tang/")?>"><span class="down">Quà tặng</span></a></li>
    
</ul>
<?php
/*$script = <<< EOJS
    $(function(){
        $('li').click(function(){
            $("li").removeClass("active");
            $(this).addClass('active');
        });
    })
EOJS;

$this->headScript()->appendScript($script);*/
?>