<?php
    $model = new Application_Model_DbTable_Articles();
    $select = $model->select();
    $select->where("article_type=?","hotro")->where("article_status=?",1);
    $datas = $model->fetchAll($select);
	$selectsky = $model->select();
	$selectsky->where("article_type=?","hotrosky")->where("article_status=?",1);
	$datasky = $model->fetchAll($selectsky);
?>
<?php if(count($datas) > 0){?>
	<div class="side-bar">
		<h2>Tìm kiếm</h2>
		<div class="search">
			<label>Giá: </label>
			<select>
			  <option select="selected">35,000 - 60,000</option>
			  <option>60,000 - 100,000</option>
			  <option>100,000 - 200,000</option>
			  <option>200,000 - 300,000</option>
			  <option>300,000 - 500,000</option>
			</select>
		</div>
	</div>
<?php }?>