<?php 
    $model = new Application_Model_DbTable_Articles();
    $datas = $model->getSlideShow();
	?>
<?php if($datas->count() > 0){?>
	<div class="theme-default" style="margin-bottom:5px;">
		<div id="slider" class="nivoSlider">
			<?php 
			foreach($datas as $k=>$row){?>
				<a target="_blank" href="<?=$row->article_title?>"><img src="timthumb.php?src=<?=$this->baseUrl("upload/$row->article_image&amp;w=980&amp;h=350")?>" alt="" title="#htmlcaption<?=$k?>" /></a>
			<?}?>
		</div>
		<?php 
		foreach($datas as $k=>$row){?>
			<div id="htmlcaption<?=$k?>" class="nivo-html-caption">
				<?=$row->article_description?>
			</div>
		<?}?>
	</div>
<?php }?>