<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="content-type" content="text/html" />
    <meta charset="utf-8" />
	<?=$this->headTitle("Login")?>
    <link href="<?=$this->baseUrl("/css/style_login.css")?>" type="text/css" rel="stylesheet" />
    <script src="<?=$this->baseUrl("/js/jquery-1.7.1.min.js")?>" type="text/javascript"></script>
    <link rel="shortcut icon" href="http://gianhangvn.com/Template/GianHang/gianhangvn.ico" type="image/x-icon"/>
</head>

<body>
<div id="header">
    <div><h1>Administrator</h1></div>
</div>
<div id="body">
    <div id="login">
        <form action="" method="post">
            <div class="input forcus">
                <span>Tài khoản</span><input type="text" name="username" />
            </div>
            <div class="input">
                <span>Mật khẩu</span><input type="password" name="password" />
            </div>
            <div class="btn">
                <input class="lg" type="submit" name="submit" value="Đăng nhập" /><input type="checkbox" /> Ghi nhớ tài khoản
            </div>
        </form>
    </div>
    <?php echo $this->layout()->content; ?>
</div>
<script>
    $(function(){
        $(".forcus input").focus();
    });
</script>
</body>
</html>